version: "3.8"

services:
  etcd-00:
    image: ${ETCD_IMAGE:-quay.io/coreos/etcd:v3.5.0}
    container_name: ${ETCD0_CONTAINER:-etcd-00}
    hostname: ${ETCD0_HOST:-etcd-00.dev.lab}
    restart: unless-stopped
    command:
      - etcd
      - --name=${ETCD0_CONTAINER}
      - --data-dir=data
      - --advertise-client-urls=http://${ETCD0_HOST}:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-advertise-peer-urls=http://${ETCD0_HOST}:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-cluster=${ETCD0_CONTAINER}=http://${ETCD0_HOST}:2380,${ETCD1_CONTAINER}=http://${ETCD1_HOST}:2380,${ETCD2_CONTAINER}=http://${ETCD2_HOST}:2380
      - --initial-cluster-state=new
      - --initial-cluster-token="${ETCD_CLUSTER_TOKEN}"
    ports:
      - 2379:2379 
      - 2380:2380
    volumes:
      - ./data/${ETCD0_CONTAINER}:/data
    networks:
      docker-vnet:
        ipv4_address: "${DOCKER_VNET_IP_BLOCK:-172.16}.${ETCD0_IP_BLOCK:-0.5}"

  etcd-01:
    image: ${ETCD_IMAGE:-quay.io/coreos/etcd:v3.5.0}
    container_name: ${ETCD1_CONTAINER:-etcd-01}
    hostname: ${ETCD1_HOST:-etcd-01.dev.lab}
    restart: unless-stopped
    command:
      - etcd
      - --name=${ETCD1_CONTAINER}
      - --data-dir=data
      - --advertise-client-urls=http://${ETCD1_HOST}:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-advertise-peer-urls=http://${ETCD1_HOST}:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-cluster=${ETCD0_CONTAINER}=http://${ETCD0_HOST}:2380,${ETCD1_CONTAINER}=http://${ETCD1_HOST}:2380,${ETCD2_CONTAINER}=http://${ETCD2_HOST}:2380
      - --initial-cluster-state=new
      - --initial-cluster-token="${ETCD_CLUSTER_TOKEN}"
    ports:
      - 23791:2379 
      - 23801:2380
    volumes:
      - ./data/${ETCD1_CONTAINER}:/data
    networks:
      docker-vnet:
        ipv4_address: "${DOCKER_VNET_IP_BLOCK:-172.16}.${ETCD1_IP_BLOCK:-0.6}"
 

  etcd-02:
    image: ${ETCD_IMAGE:-quay.io/coreos/etcd:v3.5.0}
    container_name: ${ETCD2_CONTAINER:-etcd-02}
    hostname: ${ETCD2_HOST:-etcd-02}
    restart: unless-stopped
    command:
      - etcd
      - --name=${ETCD2_CONTAINER}
      - --data-dir=data
      - --advertise-client-urls=http://${ETCD2_HOST}:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-advertise-peer-urls=http://${ETCD2_HOST}:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-cluster=${ETCD0_CONTAINER}=http://${ETCD0_HOST}:2380,${ETCD1_CONTAINER}=http://${ETCD1_HOST}:2380,${ETCD2_CONTAINER}=http://${ETCD2_HOST}:2380
      - --initial-cluster-state=new
      - --initial-cluster-token="${ETCD_CLUSTER_TOKEN}"
    ports:
      - 23792:2379 
      - 23802:2380
    volumes:
      - ./data/${ETCD2_CONTAINER}:/data

    networks:
      docker-vnet:
        ipv4_address: "${DOCKER_VNET_IP_BLOCK:-172.16}.${ETCD2_IP_BLOCK:-0.7}"

networks:
  docker-vnet:
    external: true
    name: ${DOCKER_VNET_NAME}