version: "3.8"

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=${TZ}
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      #- WATCHTOWER_MONITOR_ONLY=true
      #- WATCHTOWER_POLL_INTERVAL=30
      - WATCHTOWER_SCHEDULE=${WT_SCHEDULE}
      - WATCHTOWER_NOTIFICATIONS=${WT_NOTIFICATIONS}
      - WATCHTOWER_NOTIFICATION_GOTIFY_URL=${WT_GOTIFY_URL}
      - WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN=${WT_GOTIFY_TOKEN}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

    networks:
      docker-vnet:
        ipv4_address: "${DOCKER_VNET_IP_BLOCK:-172.16}.${TRAEFIK_IP_BLOCK:-0.3}"

networks:
  docker-vnet:
    external: true
    name: ${DOCKER_VNET_NAME}