api:
  dashboard: true
  insecure: true

log:
  level: DEBUG

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true
    network: dev-vnet
  file:
    filename: /etc/traefik/certs/certs.yml
    watch: true

