version: "3.8"

services:
  mosquitto:
    image: ${MOSQUITTO_IMAGE:-eclipse-mosquitto:2}
    container_name: ${MOSQUITTO_CONTAINER}:-mosquitto}
    volumes:
      - ./etc:/mosquitto/config:ro
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001  

    networks:
      docker-vnet:
        ipv4_address: "${DOCKER_VNET_IP_BLOCK:-172.16}.${MOSQUITTO_IP_BLOCK:-0.11}"

networks:
  docker-vnet:
    external: true
    name: ${DOCKER_VNET_NAME}